#!/bin/bash
# Submit all 4 APIs to APIs.guru via their GitHub issue creation
# APIs.guru add-api form submits to GitHub issues on APIs-guru/openapi-directory
# Manual submission required via: https://apis.guru/add-api/

echo "=== APIs.guru Submission Guide ==="
echo ""
echo "Submit each API at: https://apis.guru/add-api/"
echo ""
echo "1. SEC EDGAR Insider Trading Alerts"
echo "   URL: https://sec-edgar-alerts.up.railway.app/openapi.json"
echo "   Format: OpenAPI/Swagger"
echo "   Official: Yes"
echo "   Name: SEC EDGAR Insider Trading Alerts"
echo "   Category: Financial"
echo ""
echo "2. Healthcare License Verification"
echo "   URL: https://license-verify-api-production.up.railway.app/openapi.json"
echo "   Format: OpenAPI/Swagger"
echo "   Official: Yes"
echo "   Name: Healthcare License Verification"
echo "   Category: Open Data"
echo ""
echo "3. Marketplace Price Tracker"
echo "   URL: https://marketplace-price-api-production.up.railway.app/openapi.json"
echo "   Format: OpenAPI/Swagger"
echo "   Official: Yes"
echo "   Name: Marketplace Price Tracker"
echo "   Category: eCommerce"
echo ""
echo "4. Agent Audit Log"
echo "   URL: https://agent-audit-log.up.railway.app/openapi.json"
echo "   Format: OpenAPI/Swagger"
echo "   Official: Yes"
echo "   Name: Agent Audit Log"
echo "   Category: Security"
echo ""
echo "PREREQUISITE: Each API must serve its OpenAPI spec at /openapi.json"
echo "Check with: curl -s <base-url>/openapi.json | head -5"
